"""Tests for shade.api module."""

import pytest
import yaml

from shade.api import build, init, validate


@pytest.fixture
def project_dir(tmp_path):
    """Create a temporary project directory with config + compose."""

    def _create(shade_config: dict, compose: dict):
        shade_yml = tmp_path / "shade.yml"
        with open(shade_yml, "w") as f:
            yaml.dump(shade_config, f)

        compose_yml = tmp_path / "docker-compose.yml"
        with open(compose_yml, "w") as f:
            yaml.dump(compose, f)

        return tmp_path

    return _create


class TestValidate:
    """Test the validate API."""

    def test_valid_project(self, project_dir):
        d = project_dir(
            shade_config={
                "app": {"name": "my-app"},
                "cvm": {"domain": "example.com"},
            },
            compose={
                "services": {"my-app": {"image": "python:3.11"}},
            },
        )
        errors = validate(
            config_path=d / "shade.yml",
            compose_path=d / "docker-compose.yml",
        )
        assert errors == []

    def test_missing_app_service(self, project_dir):
        d = project_dir(
            shade_config={
                "app": {"name": "my-app"},
                "cvm": {"domain": "example.com"},
            },
            compose={
                "services": {"other-app": {"image": "python:3.11"}},
            },
        )
        errors = validate(
            config_path=d / "shade.yml",
            compose_path=d / "docker-compose.yml",
        )
        assert any("my-app" in e for e in errors)

    def test_missing_config_file(self, tmp_path):
        errors = validate(
            config_path=tmp_path / "nonexistent.yml",
            compose_path=tmp_path / "docker-compose.yml",
        )
        assert len(errors) > 0

    def test_missing_compose_file(self, tmp_path):
        shade_yml = tmp_path / "shade.yml"
        with open(shade_yml, "w") as f:
            yaml.dump({"app": {"name": "my-app"}, "cvm": {"domain": "example.com"}}, f)
        errors = validate(
            config_path=shade_yml,
            compose_path=tmp_path / "nonexistent.yml",
        )
        assert any("docker-compose.yml" in e for e in errors)


class TestBuild:
    """Test the build API."""

    def test_build_minimal(self, project_dir):
        d = project_dir(
            shade_config={
                "app": {"name": "my-app"},
                "cvm": {"domain": "example.com"},
            },
            compose={
                "services": {"my-app": {"image": "python:3.11"}},
            },
        )
        result = build(
            config_path=d / "shade.yml",
            compose_path=d / "docker-compose.yml",
            output_path=d / "docker-compose.shade.yml",
        )
        assert result.output_path.exists()
        assert result.services_count >= 3  # my-app + nginx + attestation
        assert result.routes_count == 0

        # Verify output is valid YAML
        with open(result.output_path) as f:
            content = f.read()
            assert "Generated by Shade Framework" in content
            data = yaml.safe_load(content)
            assert "services" in data

    def test_build_with_routes(self, project_dir):
        d = project_dir(
            shade_config={
                "app": {"name": "my-app"},
                "services": {"my-app": {"networks": ["proxy"]}},
                "cvm": {
                    "domain": "example.com",
                    "routes": [{"path": "/", "port": 8000}],
                },
            },
            compose={
                "services": {"my-app": {"image": "python:3.11"}},
            },
        )
        result = build(
            config_path=d / "shade.yml",
            compose_path=d / "docker-compose.yml",
            output_path=d / "docker-compose.shade.yml",
        )
        assert result.routes_count == 1

    def test_build_validation_error(self, project_dir):
        d = project_dir(
            shade_config={
                "app": {"name": "my-app"},
                "cvm": {"domain": "example.com"},
            },
            compose={
                "services": {"wrong-name": {"image": "python:3.11"}},
            },
        )
        with pytest.raises(ValueError, match="Validation failed"):
            build(
                config_path=d / "shade.yml",
                compose_path=d / "docker-compose.yml",
                output_path=d / "docker-compose.shade.yml",
            )


class TestInit:
    """Test the init API."""

    def test_init_creates_shade_yml(self, tmp_path):
        path = init(output_dir=tmp_path)
        assert path.exists()
        assert path.name == "shade.yml"

        # Verify it's valid YAML
        with open(path) as f:
            data = yaml.safe_load(f)
            assert "app" in data
            assert "cvm" in data

    def test_init_fails_if_exists(self, tmp_path):
        (tmp_path / "shade.yml").write_text("existing")
        with pytest.raises(FileExistsError):
            init(output_dir=tmp_path)
