"""Shade public API.

High-level functions for building, validating, and initializing Shade projects.
"""

import shutil
from dataclasses import dataclass
from pathlib import Path

import yaml

from shade.compose import load_user_compose, validate_route_services
from shade.config import ShadeConfig, load_shade_config
from shade.generator import generate


@dataclass
class BuildResult:
    """Result of a shade build operation."""

    output_path: Path
    services_count: int
    networks_count: int
    routes_count: int


@dataclass
class ValidateResult:
    """Result of a shade validate operation."""

    errors: list[str]
    config: ShadeConfig | None = None
    compose_data: dict | None = None
    checks: list | None = None  # list[CheckResult] from verify.py


def _validate(
    config_path: str | Path = "shade.yml",
    compose_path: str | Path = "docker-compose.yml",
    output_path: str | Path | None = None,
    env_path: str | Path | None = None,
) -> ValidateResult:
    """Core validation that returns errors and loaded artifacts.

    Args:
        config_path: Path to shade.yml.
        compose_path: Path to user's docker-compose.yml.
        output_path: Path to generated compose file (for deployment checks).
        env_path: Path to .env file (for env var checks).
    """
    from shade.verify import run_all_checks

    errors: list[str] = []

    try:
        config = load_shade_config(config_path)
    except Exception as e:
        return ValidateResult(errors=[f"Failed to load shade.yml: {e}"])

    try:
        compose_data = load_user_compose(compose_path)
    except Exception as e:
        errors.append(f"Failed to load docker-compose.yml: {e}")
        return ValidateResult(errors=errors, config=config)

    errors.extend(validate_route_services(compose_data, config))

    # Run deployment readiness checks
    compose_p = Path(compose_path)

    # Auto-detect generated compose if not explicitly provided
    if output_path:
        resolved_output = Path(output_path)
    else:
        default_output = compose_p.parent / "docker-compose.shade.yml"
        resolved_output = default_output if default_output.exists() else None

    checks = run_all_checks(
        config=config,
        user_compose=compose_data,
        output_path=resolved_output,
        env_path=Path(env_path) if env_path else compose_p.parent / ".env",
        compose_path=compose_p,
    )

    return ValidateResult(
        errors=errors, config=config, compose_data=compose_data, checks=checks
    )


def validate(
    config_path: str | Path = "shade.yml",
    compose_path: str | Path = "docker-compose.yml",
    output_path: str | Path | None = None,
    env_path: str | Path | None = None,
) -> ValidateResult:
    """Validate a Shade project configuration with deployment readiness checks.

    Args:
        config_path: Path to shade.yml.
        compose_path: Path to user's docker-compose.yml.
        output_path: Path to generated compose file (for deployment checks).
        env_path: Path to .env file (for env var checks).

    Returns:
        ValidateResult with errors and deployment warnings.
    """
    return _validate(
        config_path, compose_path, output_path=output_path,
        env_path=env_path,
    )


def build(
    config_path: str | Path = "shade.yml",
    compose_path: str | Path = "docker-compose.yml",
    output_path: str | Path = "docker-compose.shade.yml",
) -> BuildResult:
    """Build a complete Shade docker-compose from config + user compose.

    Args:
        config_path: Path to shade.yml.
        compose_path: Path to user's docker-compose.yml.
        output_path: Path to write the generated compose file.

    Returns:
        BuildResult with details about what was generated.

    Raises:
        ValueError: If validation fails.
        FileNotFoundError: If input files don't exist.
    """
    result = _validate(config_path, compose_path)

    if result.errors:
        raise ValueError("Validation failed:\n" + "\n".join(f"  - {e}" for e in result.errors))

    config = result.config
    compose_data = result.compose_data

    # Generate
    result = generate(config, compose_data)

    # Write output
    output = Path(output_path)
    with open(output, "w") as f:
        f.write("# Generated by Shade Framework - DO NOT EDIT\n")
        f.write(f"# Source: {config_path} + {compose_path}\n\n")
        yaml.dump(result, f, default_flow_style=False, sort_keys=False)

    return BuildResult(
        output_path=output,
        services_count=len(result["services"]),
        networks_count=len(result["networks"]),
        routes_count=len(config.cvm.routes),
    )


def env_list(output_path: str | Path | None = None) -> list[str]:
    """List environment variable names from the generated compose.

    Args:
        output_path: Path to generated compose file. Auto-detects docker-compose.shade.yml if None.

    Returns:
        Sorted list of env var names.
    """
    if output_path:
        path = Path(output_path)
    else:
        path = Path("docker-compose.shade.yml")

    if not path.exists():
        raise FileNotFoundError(
            f"Generated compose not found at {path}: run 'shade build' first"
        )

    with open(path) as f:
        data = yaml.safe_load(f)

    from shade.verify import extract_env_var_names

    return sorted(extract_env_var_names(data))


def init(output_dir: str | Path = ".") -> Path:
    """Create a starter shade.yml in the specified directory.

    Args:
        output_dir: Directory to create shade.yml in.

    Returns:
        Path to the created shade.yml.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    template_path = Path(__file__).parent / "templates" / "shade.yml"
    target_path = output_dir / "shade.yml"

    if target_path.exists():
        raise FileExistsError(f"shade.yml already exists at {target_path}")

    shutil.copy2(template_path, target_path)
    return target_path
