"""Shade public API.

High-level functions for building, validating, and initializing Shade projects.
"""

import shutil
from dataclasses import dataclass
from pathlib import Path

import yaml

from shade.compose import load_user_compose, validate_app_service, validate_route_services
from shade.config import ShadeConfig, load_shade_config
from shade.generator import generate
from shade.policy import (
    generate_atlas_policy as _generate_atlas_policy,
)


@dataclass
class BuildResult:
    """Result of a shade build operation."""

    output_path: Path
    services_count: int
    networks_count: int
    routes_count: int


@dataclass
class ValidateResult:
    """Result of a shade validate operation."""

    errors: list[str]
    config: ShadeConfig | None = None
    compose_data: dict | None = None


def _validate(
    config_path: str | Path = "shade.yml",
    compose_path: str | Path = "docker-compose.yml",
) -> ValidateResult:
    """Core validation that returns errors and loaded artifacts."""
    errors: list[str] = []

    try:
        config = load_shade_config(config_path)
    except Exception as e:
        return ValidateResult(errors=[f"Failed to load shade.yml: {e}"])

    try:
        compose_data = load_user_compose(compose_path)
    except Exception as e:
        errors.append(f"Failed to load docker-compose.yml: {e}")
        return ValidateResult(errors=errors, config=config)

    errors.extend(validate_app_service(compose_data, config.app.name))
    errors.extend(validate_route_services(compose_data, config))

    return ValidateResult(errors=errors, config=config, compose_data=compose_data)


def validate(
    config_path: str | Path = "shade.yml",
    compose_path: str | Path = "docker-compose.yml",
) -> list[str]:
    """Validate a Shade project configuration.

    Args:
        config_path: Path to shade.yml.
        compose_path: Path to user's docker-compose.yml.

    Returns:
        List of error messages (empty = valid).
    """
    return _validate(config_path, compose_path).errors


def build(
    config_path: str | Path = "shade.yml",
    compose_path: str | Path = "docker-compose.yml",
    output_path: str | Path = "docker-compose.shade.yml",
) -> BuildResult:
    """Build a complete Shade docker-compose from config + user compose.

    Args:
        config_path: Path to shade.yml.
        compose_path: Path to user's docker-compose.yml.
        output_path: Path to write the generated compose file.

    Returns:
        BuildResult with details about what was generated.

    Raises:
        ValueError: If validation fails.
        FileNotFoundError: If input files don't exist.
    """
    result = _validate(config_path, compose_path)

    if result.errors:
        raise ValueError("Validation failed:\n" + "\n".join(f"  - {e}" for e in result.errors))

    config = result.config
    compose_data = result.compose_data

    # Generate
    result = generate(config, compose_data)

    # Write output
    output = Path(output_path)
    with open(output, "w") as f:
        f.write("# Generated by Shade Framework - DO NOT EDIT\n")
        f.write(f"# Source: {config_path} + {compose_path}\n\n")
        yaml.dump(result, f, default_flow_style=False, sort_keys=False)

    return BuildResult(
        output_path=output,
        services_count=len(result["services"]),
        networks_count=len(result["networks"]),
        routes_count=len(config.cvm.routes),
    )


def init(output_dir: str | Path = ".") -> Path:
    """Create a starter shade.yml in the specified directory.

    Args:
        output_dir: Directory to create shade.yml in.

    Returns:
        Path to the created shade.yml.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    template_path = Path(__file__).parent / "templates" / "shade.yml"
    target_path = output_dir / "shade.yml"

    if target_path.exists():
        raise FileExistsError(f"shade.yml already exists at {target_path}")

    shutil.copy2(template_path, target_path)
    return target_path


def generate_atlas_policy(
    domain: str | None = None,
    *,
    docker_compose_file: str | None = None,
    allowed_tcb_status: list[str] | None = None,
    disable_runtime_verification: bool = False,
) -> dict:
    """Generate an Atlas-compatible policy for a CVM deployment.

    Production mode (domain provided): fetches measurements and app_compose
    from the CVM's /tdx_quote endpoint.

    Dev mode (disable_runtime_verification=True): skips runtime verification,
    no domain or measurements needed.

    Args:
        domain: CVM domain to fetch measurements from (required for production).
        docker_compose_file: Local docker-compose content to verify against
            the CVM's reported compose. Recommended for production.
        allowed_tcb_status: Allowed TCB status values. Defaults to ["UpToDate"].
        disable_runtime_verification: Skip runtime checks (dev only).

    Returns:
        Atlas policy dict ready for JSON serialization.
    """
    return _generate_atlas_policy(
        domain=domain,
        docker_compose_file=docker_compose_file,
        allowed_tcb_status=allowed_tcb_status,
        disable_runtime_verification=disable_runtime_verification,
    )
